### ISSUE TITLE
Tsoha-vertaisarviointi #1

### ISSUE THREAD

**Issue by ethanrailo** [dogamak/tsoha-crm#1]
Moi,

Sain TSOHA-vertaisarvioinnissa katselmoitavaksi harjoitustyösi. Sovelluksen idea on mielestäni hyvin selkeä ja konkreettinen ja laajuus epäilemättä riittävä.

**Käyttöliittymän kautta tehdyllä kokeellisella testaamisella tein seuraavia huomioita:**

- Mobiililaitteella käyttö ei ole kovin sujuvaa, mutta CRM-järjestelmää ei välttämättä olekaan optimoitu mobiilikäyttäjän kannalta. Tietokoneella käytettynä oli selvästi sujuvampaa.

- Virheenkäsittely oli puutteellista tai ei toiminut monessa tilanteessa okein, ainakin seuraavista saa tulokseksi HTTP500:
-- Väärä käyttäjätunnus/salasana sisäänkirjautumisessa
-- Uuden käyttäjän luominen samalla nimellä, kuin olemassaolevan käyttäjän (esim. "admin")
-- Olemattoman käyttäjän hakeminen, esim. https://tsoha-crm.herokuapp.com/view/11

- Syötteiden validointi käyttäjäkokemuksen parantamiseksi voisi olla hyvä lisä
-- Esim. sähköpostiosoite asiakastiedoissa
-- Salasanapituus voi olla tällä hetkellä vaikka yksi merkki
-- Voi luoda tyhjän käyttäjän, jolla on tyhjä salasana (https://tsoha-crm.herokuapp.com/view/46)
-- Voi luoda käyttäjän ilman salasanaa (jolla ei kuitenkaan pääse kirjautumaan sisään, koska HTTP500)

- Käyttäjänäkymä ei ehkä toimi halutusti - eli käyttäjänkin voi osoittaa toiselle käyttäjälle? Esim. https://tsoha-crm.herokuapp.com/view/1

**Koodista ja dokumentaatiosta tein seuraavia huomioita:**

- "Tämä käyttäjänluomismekanismi on käytettävissä vain testaus ja tuotantoympäristöissä." -> koodin perusteella testaus- ja kehitysympäristöissä, eli tässä varmasti vain ajatusvirhe dokumentaatiossa :-)

- config.py:ssä käytetään eri SECRET_KEY:tä eri ympäristöille. Jos tämä on merkityksellistä, niin silti avainta ei kannattaisi kovakoodata tiedostoon, vaan lukea ne vaikka sitten eri ympäristömuuttujista ENV-tiedostosta.

- Kaikki tietokantatoiminnot tehdään käytännössä "verhottuna" SQLAlchemyn modelien taakse, joka ei ymmärtääkseni ole kurssin tavoitteidenmukaista (joskin muuten kyllä ymmärrettävää ja järkevää); eli vaikka tietokannan rakennetta voikin suhteellisen yksinkertaisesti arvioida modelien kautta ja vaikutti perustellulta, niin SQL:n hyödyntämisen arviointi on sinänsä mahdotonta, koska suoranaisesti SQL-lausekkeita ei koodissa ole. SQLAlchemyä en tunne siten, että voisin ottaa järkevästi kantaa tehtyihin ratkaisuihin.

Tiivistettynä voisi todeta, että yleisesti paljon hyvää työtä, mutta valmiiksi merkatut ominaisuudet kaipaavat viimestelyä vielä sovelluksen käyttäjän näkökulmasta (valdointi & virheiden käsittely). Työn iloa!

**Comment by dogamak** [comment]
Hei, kiitos nopeasta ja kattavasta arviosta -- tekemistä tosiaan vielä riittää!

Sovellus hakee sala-avaimensa `SECRET_KEY` ympäristömuuttujasta testausympäristössä, jossa se tulee Herokun salaisuuksienhallinnasta. Kehitysympäristössä taas avaimen sisällöllä ei ole väliä, koska, no, se on kehitysympäristö -- jotain on pielessä, jos sillä alkaa olla väliä.

SQLAlchemyn tai muun ORMin käyttäminen on käsittääkseni aikaisemmin ollut kurssilla sallittua, kunhan tiedostaa sen, että ei välttämättä saa yhtä hyviä vertaisarvioita. Toivottavasti näin myös tämän toteutuksen yhteydessä.
